# Generated by Django 3.1.7 on 2021-05-31 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dinas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('shortness', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Type_article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Type_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('responsible', models.CharField(max_length=225)),
                ('information', models.CharField(max_length=225)),
                ('date', models.DateField(auto_now_add=True)),
                ('date_a', models.DateField()),
                ('date_b', models.DateField()),
                ('file', models.FileField(upload_to='')),
                ('read', models.CharField(max_length=225)),
                ('download', models.IntegerField()),
                ('size', models.CharField(max_length=225)),
                ('slug', models.SlugField()),
                ('dinas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppid.dinas')),
                ('type_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppid.type_data')),
            ],
        ),
    ]
