# Generated by Django 3.1.7 on 2021-05-31 01:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ppid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='code',
            field=models.CharField(default=django.utils.timezone.now, max_length=125),
            preserve_default=False,
        ),
    ]
