# Generated by Django 3.1.7 on 2021-06-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppid', '0002_data_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=225)),
            ],
        ),
        migrations.RemoveField(
            model_name='data',
            name='read',
        ),
        migrations.AlterField(
            model_name='data',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='data',
            name='read',
            field=models.ManyToManyField(blank=True, related_name='post_views', to='ppid.IpModel'),
        ),
    ]
