# Generated by Django 3.1.7 on 2021-06-02 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppid', '0003_auto_20210602_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='download',
        ),
        migrations.AddField(
            model_name='data',
            name='download',
            field=models.ManyToManyField(blank=True, related_name='post_download', to='ppid.IpModel'),
        ),
    ]
