# Generated by Django 3.1.7 on 2021-06-21 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppid', '0007_dinas_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='dinas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ppid.dinas'),
        ),
        migrations.AlterField(
            model_name='data',
            name='size',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
