# Generated by Django 3.1.7 on 2021-06-21 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppid', '0008_auto_20210621_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, null=True, unique=True),
        ),
    ]
