# Generated by Django 3.1.7 on 2021-08-20 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ppid', '0009_auto_20210621_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='dinas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ppid.dinas'),
        ),
        migrations.AlterField(
            model_name='data',
            name='download',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_download', to='ppid.IpModel'),
        ),
        migrations.AlterField(
            model_name='data',
            name='read',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_views', to='ppid.IpModel'),
        ),
        migrations.AlterField(
            model_name='data',
            name='size',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dinas',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dinas', to=settings.AUTH_USER_MODEL),
        ),
    ]
