# Generated by Django 3.2.6 on 2021-08-30 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppid', '0010_auto_20210820_0848'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Type_article',
        ),
        migrations.AlterField(
            model_name='data',
            name='code',
            field=models.CharField(blank=True, max_length=125),
        ),
    ]
