# Generated by Django 3.2.6 on 2021-08-30 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppid', '0011_auto_20210830_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_pemohon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_pemohon', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Form_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('telp', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50)),
                ('ktp', models.CharField(max_length=255)),
                ('purpose', models.TextField()),
                ('detail', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=125)),
                ('Information', models.TextField()),
                ('kategory_pemohon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppid.type_pemohon')),
            ],
        ),
    ]
