# Generated by Django 3.2.6 on 2021-08-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppid', '0012_form_information_type_pemohon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_information',
            name='ktp',
            field=models.FileField(max_length=255, upload_to=''),
        ),
    ]
